/**
 * routes/invites.ts — Passport invite flow (Session 7)
 *
 * POST /api/v1/passports/:id/invite
 *   Body: { channel: "sms"|"email"|"qr_print", recipient_phone?, recipient_email? }
 *   Creates invite token, sends SMS/email, returns QR code URL.
 *   Broker only.
 *
 * GET /api/v1/passports/:id/activate?t={token}
 *   Public — no auth. Validates token, returns passport preview for consumer landing page.
 *
 * POST /api/v1/passports/:id/claim
 *   Authenticated consumer. Marks invite claimed_by + activated_at.
 *   Seeds consumer's access to the passport.
 */

import { Hono } from "hono";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { supabase } from "../lib/supabase.js";
import {
  sendInviteSms,
  sendInviteEmail,
  buildActivateUrl,
  buildQrCodeUrl,
} from "../lib/notify.js";

export const invitesRouter = new Hono();

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/v1/passports/:id/invite
// ─────────────────────────────────────────────────────────────────────────────
invitesRouter.post("/:id/invite", requireAuth, requireRole("broker_pm"), async (c) => {
  const passportId = c.req.param("id");
  const userId = c.get("userId");

  // Verify broker owns this passport
  const { data: passport, error: passErr } = await supabase
    .from("passports")
    .select("id, status, created_by, brand_agent_name, brand_brokerage, properties(address_line1, city, state)")
    .eq("id", passportId)
    .single();

  if (passErr || !passport) {
    return c.json({ error: "not_found", message: "Passport not found" }, 404);
  }
  if (passport.created_by !== userId) {
    return c.json({ error: "forbidden", message: "Not your passport" }, 403);
  }

  let body: {
    channel?: "sms" | "email" | "qr_print";
    recipient_phone?: string;
    recipient_email?: string;
  };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_body", message: "Expected JSON body" }, 400);
  }

  const channel = body.channel ?? "sms";
  if (!["sms", "email", "qr_print"].includes(channel)) {
    return c.json({ error: "invalid_channel", message: "channel must be sms, email, or qr_print" }, 400);
  }
  if (channel === "sms" && !body.recipient_phone) {
    return c.json({ error: "missing_field", message: "recipient_phone required for sms channel" }, 400);
  }
  if (channel === "email" && !body.recipient_email) {
    return c.json({ error: "missing_field", message: "recipient_email required for email channel" }, 400);
  }

  // Create invite record (token auto-generated by DB default)
  const { data: invite, error: inviteErr } = await supabase
    .from("passport_invites")
    .insert({
      passport_id: passportId,
      channel,
      recipient_phone: body.recipient_phone ?? null,
      recipient_email: body.recipient_email ?? null,
      delivery_status: "pending",
    })
    .select()
    .single();

  if (inviteErr || !invite) {
    return c.json({ error: "db_error", message: inviteErr?.message ?? "Could not create invite" }, 500);
  }

  const activateUrl = buildActivateUrl(invite.token);
  const qrCodeUrl = buildQrCodeUrl(activateUrl);

  // Extract property address for display
  const prop = (passport.properties as Array<{ address_line1: string; city: string; state: string }>)[0];
  const propertyAddress = prop
    ? `${prop.address_line1}, ${prop.city}, ${prop.state}`
    : "your new property";

  const agentName = passport.brand_agent_name ?? "Your Agent";
  const brokerage = passport.brand_brokerage ?? null;

  // ── Deliver ─────────────────────────────────────────────────────────────
  let deliveryMeta: Record<string, string> = {};
  let deliveryError: string | null = null;

  try {
    if (channel === "sms" && body.recipient_phone) {
      const result = await sendInviteSms(body.recipient_phone, activateUrl, agentName);
      deliveryMeta = { twilio_sid: result.sid, twilio_status: result.status };

      await supabase
        .from("passport_invites")
        .update({ delivery_status: "sent", twilio_message_sid: result.sid, delivered_at: new Date().toISOString() })
        .eq("id", invite.id);

    } else if (channel === "email" && body.recipient_email) {
      const result = await sendInviteEmail(
        body.recipient_email,
        activateUrl,
        agentName,
        brokerage,
        propertyAddress,
        qrCodeUrl
      );
      deliveryMeta = { resend_id: result.id };

      await supabase
        .from("passport_invites")
        .update({ delivery_status: "sent", resend_message_id: result.id, delivered_at: new Date().toISOString() })
        .eq("id", invite.id);

    } else if (channel === "qr_print") {
      // QR print — no delivery needed, mark sent immediately
      await supabase
        .from("passport_invites")
        .update({ delivery_status: "sent", delivered_at: new Date().toISOString() })
        .eq("id", invite.id);
    }
  } catch (err) {
    deliveryError = err instanceof Error ? err.message : String(err);
    console.error(`[invite:${invite.id}] delivery failed: ${deliveryError}`);

    await supabase
      .from("passport_invites")
      .update({ delivery_status: "failed" })
      .eq("id", invite.id);
  }

  // Update passport status to "sent" if still draft
  if (passport.status === "draft") {
    await supabase
      .from("passports")
      .update({ status: "sent" })
      .eq("id", passportId);
  }

  return c.json({
    invite_id: invite.id,
    token: invite.token,
    channel,
    activate_url: activateUrl,
    qr_code_url: qrCodeUrl,
    delivery: deliveryError
      ? { status: "failed", error: deliveryError }
      : { status: "sent", ...deliveryMeta },
  }, deliveryError ? 207 : 201);
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/v1/passports/:id/activate?t={token}
// Public — validates token, returns passport preview
// ─────────────────────────────────────────────────────────────────────────────
invitesRouter.get("/:id/activate", async (c) => {
  const passportId = c.req.param("id");
  const token = c.req.query("t");

  if (!token) {
    return c.json({ error: "missing_token", message: "Token required" }, 400);
  }

  // Validate token
  const { data: invite, error: inviteErr } = await supabase
    .from("passport_invites")
    .select("id, token, passport_id, channel, claimed_by, activated_at, delivery_status")
    .eq("token", token)
    .eq("passport_id", passportId)
    .single();

  if (inviteErr || !invite) {
    return c.json({ error: "invalid_token", message: "Token not found or invalid" }, 404);
  }

  if (invite.claimed_by && invite.activated_at) {
    return c.json({ error: "already_claimed", message: "This passport has already been activated" }, 409);
  }

  // Fetch passport preview
  const { data: passport } = await supabase
    .from("passports")
    .select(`
      id, status, brand_agent_name, brand_brokerage, brand_photo_url,
      brand_contact_email, brand_contact_phone, appliance_count,
      properties(address_line1, address_line2, city, state, zip)
    `)
    .eq("id", passportId)
    .single();

  if (!passport) {
    return c.json({ error: "not_found", message: "Passport not found" }, 404);
  }

  // Fetch appliance summary (type + make only — no sensitive details before claim)
  const { data: junctionRows } = await supabase
    .from("passport_appliances")
    .select("appliance_id")
    .eq("passport_id", passportId);

  const applianceIds = (junctionRows ?? []).map((r) => r.appliance_id);
  let applianceSummary: { appliance_type: string; make: string }[] = [];
  if (applianceIds.length > 0) {
    const { data } = await supabase
      .from("appliances")
      .select("appliance_type, make")
      .in("id", applianceIds);
    applianceSummary = data ?? [];
  }

  // Mark invite as opened
  await supabase
    .from("passport_invites")
    .update({ delivery_status: "opened" })
    .eq("id", invite.id)
    .eq("delivery_status", "sent"); // only update if was sent, not already opened/claimed

  return c.json({
    passport_preview: {
      id: passport.id,
      status: passport.status,
      property: passport.properties,
      agent: {
        name: passport.brand_agent_name,
        brokerage: passport.brand_brokerage,
        photo_url: passport.brand_photo_url,
        email: passport.brand_contact_email,
        phone: passport.brand_contact_phone,
      },
      appliance_count: passport.appliance_count,
      appliance_summary: applianceSummary,
    },
    invite_id: invite.id,
    token: invite.token,
    requires_auth: true,
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/v1/passports/:id/claim
// Authenticated consumer — claims the invite, activates passport access
// ─────────────────────────────────────────────────────────────────────────────
invitesRouter.post("/:id/claim", requireAuth, async (c) => {
  const passportId = c.req.param("id");
  const userId = c.get("userId");

  let body: { token?: string };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_body", message: "Expected JSON body with token" }, 400);
  }

  if (!body.token) {
    return c.json({ error: "missing_field", message: "token is required" }, 400);
  }

  // Find and validate token
  const { data: invite, error: inviteErr } = await supabase
    .from("passport_invites")
    .select("id, passport_id, claimed_by, activated_at")
    .eq("token", body.token)
    .eq("passport_id", passportId)
    .single();

  if (inviteErr || !invite) {
    return c.json({ error: "invalid_token", message: "Token not found or invalid" }, 404);
  }

  if (invite.claimed_by && invite.activated_at) {
    // Already claimed — idempotent if same user
    if (invite.claimed_by === userId) {
      return c.json({ status: "already_activated", message: "You have already activated this passport" });
    }
    return c.json({ error: "already_claimed", message: "This token has already been used" }, 409);
  }

  // Claim the invite
  const now = new Date().toISOString();
  const { error: claimErr } = await supabase
    .from("passport_invites")
    .update({ claimed_by: userId, activated_at: now, delivery_status: "opened" })
    .eq("id", invite.id);

  if (claimErr) {
    return c.json({ error: "db_error", message: claimErr.message }, 500);
  }

  // Activate the passport
  await supabase
    .from("passports")
    .update({ status: "activated", activated_at: now })
    .eq("id", passportId)
    .eq("status", "sent"); // only advance from sent → activated

  // Ensure consumer has a profiles row (should exist from signup trigger)
  const { data: profile } = await supabase
    .from("profiles")
    .select("id, onboarded_via")
    .eq("id", userId)
    .single();

  if (profile && !profile.onboarded_via) {
    await supabase
      .from("profiles")
      .update({ onboarded_via: "passport_invite" })
      .eq("id", userId);
  }

  return c.json({
    status: "activated",
    passport_id: passportId,
    invite_id: invite.id,
    activated_at: now,
    message: "Passport activated — you can now access your appliances",
  });
});
